### PR TITLE
Apply Zooniverse layout and branding

### LINKED ISSUE #11: Add page landmarks.
Pages are an unstructured collection of nested `div` tags. They should use [sectioning elements](https://www.w3.org/TR/wai-aria-practices/examples/landmarks/HTML5.html) to break each page into landmark regions.

### PR DESCRIPTION
**Pull request by eatyourgreens**
You can preview the site styles at https://talk.sciencegossip.org/recent and the original Talk design for reference https://talk.sciencegossip.org/.

I'll keep the preview site updated as this PR changes.

Closes #11 by adding `<main>` and `<aside>` regions to all pages.

### CODE REVIEW

**Comment by beckyrother** [comment]
This is looking great, thanks! I added some styling/spacing reference to the DSM: https://projects.invisionapp.com/dsm/zooniverse/primary-brand/folder/components/5ea9958f0c1c09c215eec42d

**Comment by eatyourgreens** [comment]
Thanks! Tailwind handles spacing based on the root font size, so I chose to use `.5rem` and `1rem`. Easy to change, though, and we can override Tailwind’s default scale with our own.

**Comment by eatyourgreens** [comment]
I've increased the spacing between elements and under headings. Hopefully, it looks much better now.

**Comment by beckyrother** [comment]
Looks great! Is it possible to group lines of text from the same post closer together? 
image

**Comment by eatyourgreens** [comment]
I've removed the default paragraph spacing and updated the spacing for those lists. I've set the paragraph spacing to `1rem` for paragraphs inside comments. Paragraph spacing might have gone a bit wonky elsewhere.

**Comment by eatyourgreens** [comment]
This kind of grew to include expanding the page metadata and fixing the page markup (#11) but I think it's done now so I'm removing the Draft status. Latest version is published at https://talk.sciencegossip.org/recent.

**Comment by beckyrother** [comment]
👋 This is looking good! Let me know when you'd like another review. 

One thing that's come up elsewhere is a consistent header between our apps – I sent [this](https://projects.invisionapp.com/d/main/#/console/12924056/415563080/preview) to Chelsea for the NASA Landsat project she's working on and could be used here as well

**Comment by eatyourgreens** [comment]
I'd like to get this PR merged, so if you have time to give the site another review that would be brilliant. The teal header looks good. I'll add it in to the PR. My only concern would be that it might take up too much vertical space but we can test that once it's added to the pages.

**Comment by eatyourgreens** [comment]
New header looks good to me. I used the `brand` colour from the Zoo theme as the background.

Screenshot of a Talk user profile page, with the new teal header section at the top of the page.

**Comment by eatyourgreens** [comment]
Cheers!

**Comment by eatyourgreens** [comment]
The grid spacing for the navigation is tightened up now. https://talk.sciencegossip.org/subjects/ASC0000ayl/

**Comment by eatyourgreens** [comment]
@beckyrother I've merged this but if any new design issues come up, please do open issues here.

**Pull request merged**
